"""add job source and queries

Revision ID: 1da8ea9487ef
Revises: da19fea7314f
Create Date: 2026-06-20 15:36:54.911467
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1da8ea9487ef'
down_revision: str | None = 'da19fea7314f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=32), nullable=False, server_default='google_maps'))
        batch_op.add_column(sa.Column('queries', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('queries')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
