"""add find-leads search params to jobs

Revision ID: a0dd80624b1d
Revises: 356efb9588c3
Create Date: 2026-06-20 10:44:20.215121
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a0dd80624b1d'
down_revision: str | None = '356efb9588c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('radius_m', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lang', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('max_results', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extract_emails', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('extract_emails')
        batch_op.drop_column('max_results')
        batch_op.drop_column('lang')
        batch_op.drop_column('radius_m')
        batch_op.drop_column('keywords')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
