"""add user target

Revision ID: da19fea7314f
Revises: 9af59f5f423c
Create Date: 2026-06-20 13:12:24.541745
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'da19fea7314f'
down_revision: str | None = '9af59f5f423c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('target')

    # ### end Alembic commands ###
